### PR TITLE
File issue allowed fixed

### PR DESCRIPTION
**Pull request by ColonelSanderson**
@payten as per the previous PR, the field copy operations should work fine outside of the alter_table block now.

### CODE REVIEW

**Comment by payten** [comment]
@ColonelSanderson hitting an `duplicate migration 89` on this.

Also from #15, there's the issue of the as_cartography and MAP dependencies on the `file_issue_allowed` field and there'll be some changes required to handle the string value vs the boolean. Also there's the issue of what the different enum values mean for the MAP and what the agency users see.

If you're not going to update those systems can you put a task in pivotal and Megan can prioritise against other MVP work.

**Comment by marktriggs** [comment]
@ColonelSanderson I'm hitting an exception migrating from QA:

```
     [java] I, [2020-01-22T15:28:33.707855 #24220]  INFO -- : Begin applying migration version 100, direction: up
     [java] E, [2020-01-22T15:28:33.759820 #24220] ERROR -- : Java::ComMysqlJdbcExceptionsJdbc4::MySQLIntegrityConstraintViolationException: Cannot add or update a child row: a foreign key constraint fails (`archivesspace`.`#sql-6b2_b51`, CONSTRAINT `runcorn_file_issue_allowed_digital_fk` FOREIGN KEY (`file_issue_allowed_id`) REFERENCES `enumeration_value` (`id`)): ALTER TABLE `digital_representation` ADD CONSTRAINT `runcorn_file_issue_allowed_digital_fk` FOREIGN KEY (`file_issue_allowed_id`) REFERENCES `enumeration_value`(`id`)
```

I think that's the create_enum ordering issue that @payten mentioned previously.

**Comment by ColonelSanderson** [comment]
@marktriggs Hmm I hadn't had an issue with that.
@payten Pivotal task added.

**Comment by ColonelSanderson** [comment]
@marktriggs @payten if there's nothing else outstanding here, can you please merge this?

**Comment by marktriggs** [comment]
Merged it manually along with the changes needed to keep the MAP working.  I had to make a few little migration adjustments to get it running against the UAT environment, which are here for reference:

https://github.com/hudmol/as_runcorn/commit/264b59d15d3aae1ce99be242083741791e305892

**Pull request merged**
