### PR TITLE
167935652/agency changes

### PR DESCRIPTION
**Pull request by ColonelSanderson**

### CODE REVIEW

**Comment by payten** [comment]
Looks good @ColonelSanderson.  I think the migration indices are duplicates -- if you rebase and re-number I think we're good to merge.

**Comment by ColonelSanderson** [comment]
@payten What duplicates, sorry? Do you mean combine the migration files into 048?

**Comment by marktriggs** [comment]
(playing the role of Payten because why not...)

We've added a bunch of migrations since your branch was taken:

  https://github.com/hudmol/as_runcorn/tree/master/migrations

So you'll just need to renumber your `048`, `049` & `050` to `058`, `059` & `060`.  No need to combine them unless that makes you happy, in which case don't not do that!

**Comment by ColonelSanderson** [comment]
@marktriggs I think it got there in the end.

**Comment by marktriggs** [comment]
Yep, cool.  I've just merged from the cmdline and pushed it to master, so all should be well!

**Comment by payten** [comment]
Ah, sorry, I definitely could've been clearer. Thanks both!

**Pull request closed without merging**
